# Generated by Django 4.2.3 on 2024-02-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='doctor',
            new_name='user',
        ),
    ]
