# Generated by Django 4.2.3 on 2024-02-14 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_staffcontactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Collage',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Form4_Certificate',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Form6_Certificate',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Profile_Image',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='Univercity_Certificate',
        ),
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='course',
        ),
        migrations.AddField(
            model_name='staffcontactinfo',
            name='Professional',
            field=models.CharField(choices=[('Eye', 'Eye'), ('Teeth', 'Teeth'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffcontactinfo',
            name='Level_Of_Education',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='staffcontactinfo',
            name='User_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=40),
        ),
    ]
