# Generated by Django 4.2.3 on 2024-03-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_remove_staffcontactinfo_collage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='Symptoms',
            field=models.CharField(choices=[('NHIF', 'NHIF'), ('Cash payment', 'Cash payment')], max_length=40),
        ),
    ]
