# Generated by Django 4.2.3 on 2024-03-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_alter_patientinfo_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='Symptoms',
            field=models.TextField(),
        ),
    ]
