# Generated by Django 4.2.3 on 2024-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0017_iopb_iopa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystaff',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
