# Generated by Django 4.2.3 on 2024-03-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0020_vitreousr_vitreousl_retinar_retinal_pupilr_pupill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjunctivar',
            old_name='Stutus',
            new_name='Status',
        ),
    ]
