# Generated by Django 4.2.3 on 2024-03-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0021_rename_stutus_conjunctivar_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acl',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='acr',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='conjunctival',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='corneal',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='cornear',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='eyelidl',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='eyelidr',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='irisl',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='irisr',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='lensl',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='lensr',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='pupill',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='pupilr',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='retinal',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='retinar',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='vitreousl',
            old_name='Stutus',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='vitreousr',
            old_name='Stutus',
            new_name='Status',
        ),
    ]
