# Generated by Django 3.2.25 on 2024-04-02 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0022_rename_stutus_acl_status_rename_stutus_acr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Place',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('NHIF', 'NHIF'), ('Cash payment', 'Cash payment')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
