# Generated by Django 3.2.25 on 2024-04-04 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0023_auto_20240402_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontactinfo',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=40),
        ),
    ]
